import { Comfortaa, JetBrains_Mono, Playfair_Display, Poppins } from "next/font/google";
import "remixicon/fonts/remixicon.css";
import "./globals.css";
import "./landing.css";
import { GoogleOAuthProvider } from "@react-oauth/google";
import { UserProvider } from "@/data/UserContext";
import ErrorBoundary from "@/components/common/ErrorBoundary";
import EnvDebug from "@/components/EnvDebug"; 

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"], // light → bold
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "900"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
  weight: ["200", "400", "600", "700"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"], // adjust as needed
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body
        className={`${comfortaa.variable} ${playfair.variable} ${jetbrainsMono.variable} ${poppins.variable} antialiased`}
      >
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || "1068912069395-pjjgo5vkfm478a42l292uhlj5u5t23ro.apps.googleusercontent.com"}>
          <ErrorBoundary>
            <UserProvider>
              {children}
            </UserProvider>
          </ErrorBoundary>
        </GoogleOAuthProvider>
        <EnvDebug />
      </body>
    </html>
  );
}
